/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_cliente_servidor.vista;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author lincy
 */
public class Menu_Principal_Vista extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal_Vista
     */
    
    CardLayout Vista1;
    CardLayout Vista2;
    CardLayout Vista3;
    CardLayout Vista4;
    CardLayout Vista5;
    CardLayout Vista6;
    CardLayout Vista7;
    
    Pln_Formulario_Registro Pln_Formulario_Registro = new Pln_Formulario_Registro();
    Pln_Crear_Usauario Pln_Crear_Usauario = new Pln_Crear_Usauario();
    Pln_Info_Cliente Pln_Info_Cliente = new Pln_Info_Cliente();
    Pln_Iniciar_Sesion Pln_Iniciar_Sesion = new Pln_Iniciar_Sesion();
    Pln_Tipo_Poliza Pln_Tipo_Poliza = new Pln_Tipo_Poliza();
    Pln_Pago_Poliza Pln_Pago_Poliza = new Pln_Pago_Poliza();
    Pln_Formulario_Registro_Vehiculo Pln_Formulario_Registro_Vehiculo = new Pln_Formulario_Registro_Vehiculo();
    
    
    
    public Menu_Principal_Vista() {
        initComponents();

        PnlOpciones.setPreferredSize(new java.awt.Dimension(260, 650)); // 
        PnlCards.setPreferredSize(new java.awt.Dimension(600, 650)); // 

        Vista1 = (CardLayout) PnlCards.getLayout();
        Vista2 = (CardLayout) PnlCards.getLayout();
        Vista3 = (CardLayout) PnlCards.getLayout();
        Vista4 = (CardLayout) PnlCards.getLayout();
        Vista5 = (CardLayout) PnlCards.getLayout();
        Vista6 = (CardLayout) PnlCards.getLayout();
        Vista7 = (CardLayout) PnlCards.getLayout();

        PnlCards.add(Pln_Iniciar_Sesion, "Iniciar Sesion");
        Vista3.show(PnlCards, "Iniciar Sesion");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlOpciones = new javax.swing.JPanel();
        Btn_Formulario_Registro = new javax.swing.JButton();
        Btn_Tipo_Poliza = new javax.swing.JButton();
        Btn_Crear_Usuario = new javax.swing.JButton();
        Btn_Info_Cliente = new javax.swing.JButton();
        Btn_Pago_Poliza = new javax.swing.JButton();
        Btn_Salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Btn_Iniciar_Sesion = new javax.swing.JButton();
        PnlCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlOpciones.setRequestFocusEnabled(false);

        Btn_Formulario_Registro.setText("Formulario Registro Cliente.");
        Btn_Formulario_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Formulario_RegistroActionPerformed(evt);
            }
        });

        Btn_Tipo_Poliza.setText("Tipos de Poliza.");
        Btn_Tipo_Poliza.setToolTipText("");
        Btn_Tipo_Poliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tipo_PolizaActionPerformed(evt);
            }
        });

        Btn_Crear_Usuario.setText("Crear Usuario.");
        Btn_Crear_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Crear_UsuarioActionPerformed(evt);
            }
        });

        Btn_Info_Cliente.setText("Informacion Cliente.");
        Btn_Info_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Info_ClienteActionPerformed(evt);
            }
        });

        Btn_Pago_Poliza.setText("Pago de Poliza.");
        Btn_Pago_Poliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Pago_PolizaActionPerformed(evt);
            }
        });

        Btn_Salir.setText("Salir");
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        jButton1.setText("Formulario Registro Vehiculo.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Btn_Iniciar_Sesion.setText("Iniciar sesion.");
        Btn_Iniciar_Sesion.setToolTipText("");
        Btn_Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Iniciar_SesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlOpcionesLayout = new javax.swing.GroupLayout(PnlOpciones);
        PnlOpciones.setLayout(PnlOpcionesLayout);
        PnlOpcionesLayout.setHorizontalGroup(
            PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Iniciar_Sesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Tipo_Poliza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Info_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Pago_Poliza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Formulario_Registro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Crear_Usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        PnlOpcionesLayout.setVerticalGroup(
            PnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlOpcionesLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(Btn_Iniciar_Sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Crear_Usuario)
                .addGap(18, 18, 18)
                .addComponent(Btn_Formulario_Registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Tipo_Poliza)
                .addGap(13, 13, 13)
                .addComponent(Btn_Info_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Pago_Poliza)
                .addGap(12, 12, 12)
                .addComponent(Btn_Salir)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        PnlCards.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(PnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(640, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Formulario_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Formulario_RegistroActionPerformed
        PnlCards.add(Pln_Formulario_Registro, "Formulario");
        Vista1.show(PnlCards, "Formulario");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_Btn_Formulario_RegistroActionPerformed

    private void Btn_Info_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Info_ClienteActionPerformed
         PnlCards.add(Pln_Info_Cliente, "Informacion Cliente");
        Vista5.show(PnlCards, "Informacion Cliente");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_Btn_Info_ClienteActionPerformed

    private void Btn_Tipo_PolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tipo_PolizaActionPerformed
         PnlCards.add(Pln_Tipo_Poliza, "Tipo Poliza");
        Vista4.show(PnlCards, "Tipo Poliza");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_Btn_Tipo_PolizaActionPerformed

    private void Btn_Crear_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Crear_UsuarioActionPerformed
        PnlCards.add(Pln_Crear_Usauario, "Usuario Nuevo");
        Vista2.show(PnlCards, "Usuario Nuevo");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_Btn_Crear_UsuarioActionPerformed

    private void Btn_Pago_PolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Pago_PolizaActionPerformed
        PnlCards.add(Pln_Pago_Poliza, "Pago de Poliza");
        Vista6.show(PnlCards, "Pago de Poliza");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_Btn_Pago_PolizaActionPerformed

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     PnlCards.add(Pln_Formulario_Registro_Vehiculo, "Formulario");
        Vista1.show(PnlCards, "Formulario");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_Iniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Iniciar_SesionActionPerformed
        PnlCards.add(Pln_Iniciar_Sesion, "Iniciar Sesion");
        Vista3.show(PnlCards, "Iniciar Sesion");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_Btn_Iniciar_SesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Menu_Principal_Vista frame = new Menu_Principal_Vista();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Menu_Principal_Vista().setVisible(true);
                // Centrar el JFrame en la pantalla
                frame.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Crear_Usuario;
    private javax.swing.JButton Btn_Formulario_Registro;
    private javax.swing.JButton Btn_Info_Cliente;
    private javax.swing.JButton Btn_Iniciar_Sesion;
    private javax.swing.JButton Btn_Pago_Poliza;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JButton Btn_Tipo_Poliza;
    private javax.swing.JPanel PnlCards;
    private javax.swing.JPanel PnlOpciones;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
