/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_cliente_servidor.vista;

/**
 *
 * @author lincy
 */
public class Pln_Tipo_Poliza extends javax.swing.JPanel {

    /**
     * Creates new form Info_Cliente
     */
    public Pln_Tipo_Poliza() {
        initComponents();
    }
private void setPanelSize() {
        this.setPreferredSize(new java.awt.Dimension(600, 650));
        this.setMinimumSize(new java.awt.Dimension(600, 650));
        this.setMaximumSize(new java.awt.Dimension(600, 650));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlb_Seguro_A_Terceros = new javax.swing.JLabel();
        Jlb_Seguro_B_Terceros_Ext = new javax.swing.JLabel();
        Jlb_Seguro_C_Todo = new javax.swing.JLabel();
        Jlb_Seguro_D_Todo_Fran = new javax.swing.JLabel();
        Jlb_Titulo_Poliza = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Jt_Cobertura_A = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jt_Cobertura_B = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Jt_Cobertura_C = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Jt_Cobertura_D = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(598, 615));

        Jlb_Seguro_A_Terceros.setText("(A)  Seguro a Terceros");

        Jlb_Seguro_B_Terceros_Ext.setText("(B)  Seguros a terceros ampliados ");

        Jlb_Seguro_C_Todo.setText("(C) Seguros a Todo Riesgo");

        Jlb_Seguro_D_Todo_Fran.setText("(D) Todo Riesgo con Franquicia");

        Jlb_Titulo_Poliza.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Jlb_Titulo_Poliza.setText("Polizas ");

        Jt_Cobertura_A.setColumns(20);
        Jt_Cobertura_A.setRows(5);
        Jt_Cobertura_A.setText(" Las pólizas a terceros incluyen el seguro de responsabilidad civil que cubre las lesiones causadas a \nterceros y los daños producidos a los ocupantes, además, en caso de accidente, si el conductor del\n otro vehículo sufre daños graves o fallece, la compañía aseguradora indemnizará con la cuantía que\n estuviera estipulada por la ley. Los topes que se han establecido por la ley a la hora de pagar\n indemnizaciones son los siguientes:  Daños Materiales o transporte de animales:\n Se ha establecido un máximo de 99.871 euros por siniestro Daños personales a terceros:\n Se establecido un máximo de 349.550 por persona.");
        jScrollPane3.setViewportView(Jt_Cobertura_A);

        Jt_Cobertura_B.setColumns(20);
        Jt_Cobertura_B.setRows(5);
        Jt_Cobertura_B.setText("La principal diferencia que tienen estos seguros con los seguros a terceros es que te ofrecen protección \ncontra robos, lunas e incendios y es bastante útil en la mayoría de los casos. ");
        jScrollPane2.setViewportView(Jt_Cobertura_B);

        Jt_Cobertura_C.setColumns(20);
        Jt_Cobertura_C.setRows(5);
        Jt_Cobertura_C.setText("En los seguros a todo riesgo están cubiertos tanto los ocupantes del vehículo como el conductor, \npasando por ambos vehículos y los ocupantes de terceros. Es la opción más completa aunque también\n la más costosa pero si tu vehículo es nuevo o tiene poco tiempo es la opción más recomendable\n debido a la gran cantidad de coberturas extra que nos ofrece.");
        jScrollPane4.setViewportView(Jt_Cobertura_C);

        Jt_Cobertura_D.setColumns(20);
        Jt_Cobertura_D.setRows(5);
        Jt_Cobertura_D.setText("Los Seguros a Todo Riesgo con Franquicia se diferencian con los seguros a todo riesgo en que en caso\n de sufrir daños el vehículo la resolución del problema se haría una parte por el asegurado y una parte\n por una franquicia que estipula el precio máximo de reparación. Este tipo de seguros suele ser más \nutilizado por gente que tenga coches de lujo o que nunca tienen accidentes en carretera ya que si sufres \nsiniestros leves con frecuencia, este seguro a la larga no te compensa.");
        jScrollPane5.setViewportView(Jt_Cobertura_D);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                                .addComponent(jScrollPane4))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jlb_Titulo_Poliza, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(Jlb_Seguro_A_Terceros, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(Jlb_Seguro_B_Terceros_Ext, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(Jlb_Seguro_C_Todo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(Jlb_Seguro_D_Todo_Fran)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_Titulo_Poliza)
                    .addComponent(Jlb_Seguro_A_Terceros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlb_Seguro_B_Terceros_Ext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlb_Seguro_C_Todo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jlb_Seguro_D_Todo_Fran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlb_Seguro_A_Terceros;
    private javax.swing.JLabel Jlb_Seguro_B_Terceros_Ext;
    private javax.swing.JLabel Jlb_Seguro_C_Todo;
    private javax.swing.JLabel Jlb_Seguro_D_Todo_Fran;
    private javax.swing.JLabel Jlb_Titulo_Poliza;
    private javax.swing.JTextArea Jt_Cobertura_A;
    private javax.swing.JTextArea Jt_Cobertura_B;
    private javax.swing.JTextArea Jt_Cobertura_C;
    private javax.swing.JTextArea Jt_Cobertura_D;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
